name: Build
on: [ 'push','workflow_dispatch' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3
      - name: Install NPM
        run: npm run ci
      - name: Build App
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build
          name: build-files
