name: Test React App
on: push

jobs:
  test-my-project:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: install node_modules
        run: npm ci
      - name: Test app
        run: npm run test
